apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: claims-api
  description: "This API provides functionality around the C&P Benefit Claim and seeks to provide simple and concise mechanisms to create and view claim information."
  annotations:
    github.com/project-slug: dstrivelli/claims-api
    backstage.io/techdocs-ref: url:https://github.com/dstrivelli/claims-api
spec:
  type: openapi
  lifecycle: production
  owner: "claims"
  definition:
    $text: https://github.com/dstrivelli/claims-api/blob/master/openapi.yaml
